CREATE DATABASE BoockStore;

CREATE TABLE publisher(id SERIAL PRIMARY KEY, name VARCHAR(60) NOT NULL);
CREATE TABLE book(id SERIAL PRIMARY KEY, title VARCHAR(60) NOT NULL, id_publisher INTEGER REFERENCES publisher(id));
CREATE TABLE shop(id SERIAL PRIMARY KEY, name VARCHAR(60) NOT NULL);
CREATE TABLE stock(id SERIAL PRIMARY KEY,id_book INTEGER REFERENCES book(id), id_shop INTEGER REFERENCES shop(id), count INTEGER NOT NULL);
CREATE TABLE sale(id SERIAL PRIMARY KEY, price NUMERIC(5, 2) NOT NULL,  date_sale DATE NOT NULL, id_stock INTEGER REFERENCES stock(id), count INTEGER NOT NULL);
